// BreedIQ — Public ICS Calendar Subscription Feed
//
// GET /api/calendar/feed/:token.ics
//
// Public endpoint — NO auth header required (calendar apps like Google Calendar,
// Apple Calendar, and Outlook don't send Authorization headers when subscribing
// to a URL). Access is gated entirely by an unguessable token stored on the
// user's profile (profiles.calendar_feed_token). The token is generated by
// POST /api/calendar/subscription and can be rotated via DELETE.
//
// Returns: text/calendar; charset=utf-8  with a valid VCALENDAR containing
// the same events the authenticated /api/litters/calendar endpoint returns:
//   - Heat windows (projected from dogs.last_heat_date + avg_heat_cycle_days)
//   - Vet visits overdue (>1 year since last visit)
//   - Litter lifecycle events: breed, ultrasound, x-ray, due, whelp, go-home
//
// All events are emitted as all-day VEVENTs (DTSTART;VALUE=DATE) which renders
// cleanly in every calendar client without needing VTIMEZONE.
//
// Invalid token → 404 (this is a public-by-URL endpoint; we do NOT reveal
// whether a token used to exist).

import { getServiceClient } from '../../../lib/supabase.js';

const DAY_MS = 24 * 60 * 60 * 1000;

const EVENT_META = {
    heat_due:   { label: 'Heat window' },
    breed:      { label: 'Breeding' },
    ultrasound: { label: 'Ultrasound' },
    xray:       { label: 'X-ray' },
    due:        { label: 'Due date' },
    whelp:      { label: 'Whelp' },
    go_home:    { label: 'Go home' },
    vet_due:    { label: 'Vet visit due' }
};

// How far forward/back to emit events. ICS feeds should include some past
// window so already-synced events don't disappear from subscriber calendars
// right after they happen, plus a generous forward window for planning.
const WINDOW_PAST_DAYS = 30;
const WINDOW_FUTURE_DAYS = 365;

// ─── Helpers ─────────────────────────────────────────────────

function isoDate(d) {
    if (!d) return null;
    const dt = (d instanceof Date) ? d : new Date(d);
    if (isNaN(dt.getTime())) return null;
    return dt.toISOString().slice(0, 10);
}

function withinWindow(dateStr, startMs, endMs) {
    if (!dateStr) return false;
    const t = new Date(dateStr).getTime();
    if (isNaN(t)) return false;
    return t >= startMs && t <= endMs;
}

// ICS line folding — RFC 5545 requires lines to be <= 75 octets; fold with CRLF + space.
function foldLine(line) {
    const MAX = 74;
    if (line.length <= MAX) return line;
    let out = '';
    let i = 0;
    while (i < line.length) {
        if (i === 0) {
            out += line.slice(0, MAX);
            i = MAX;
        } else {
            out += '\r\n ' + line.slice(i, i + MAX - 1);
            i += MAX - 1;
        }
    }
    return out;
}

// Escape ICS text field per RFC 5545 3.3.11
function escapeText(s) {
    if (s == null) return '';
    return String(s)
        .replace(/\\/g, '\\\\')
        .replace(/;/g, '\\;')
        .replace(/,/g, '\\,')
        .replace(/\r\n|\n|\r/g, '\\n');
}

// YYYY-MM-DD → YYYYMMDD (ICS DATE value)
function icsDate(iso) {
    return iso.replace(/-/g, '');
}

// Date → YYYYMMDDTHHMMSSZ (ICS UTC DATE-TIME)
function icsDateTimeUtc(d) {
    const pad = n => String(n).padStart(2, '0');
    return (
        d.getUTCFullYear().toString() +
        pad(d.getUTCMonth() + 1) +
        pad(d.getUTCDate()) +
        'T' +
        pad(d.getUTCHours()) +
        pad(d.getUTCMinutes()) +
        pad(d.getUTCSeconds()) +
        'Z'
    );
}

// Add N days to a YYYY-MM-DD string → YYYY-MM-DD
function addDays(iso, n) {
    const d = new Date(iso + 'T00:00:00Z');
    d.setUTCDate(d.getUTCDate() + n);
    return d.toISOString().slice(0, 10);
}

// ─── Event build ─────────────────────────────────────────────

async function buildEvents(supabase, ownerId) {
    const now = Date.now();
    const windowStart = now - WINDOW_PAST_DAYS * DAY_MS;
    const windowEnd = now + WINDOW_FUTURE_DAYS * DAY_MS;

    // Include sub-breeder dogs/litters if this profile is a program owner.
    // Mirrors /api/litters/calendar.js.
    const { data: relationships } = await supabase
        .from('breeder_relationships')
        .select('breeder_id')
        .eq('owner_id', ownerId)
        .eq('status', 'active');

    const breederIds = (relationships || []).map(r => r.breeder_id);
    const allUserIds = [ownerId, ...breederIds];

    const { data: dogs } = await supabase
        .from('dogs')
        .select('id, name, call_name, last_heat_date, avg_heat_cycle_days, vet_last_visit, status')
        .in('user_id', allUserIds);

    const { data: litters } = await supabase
        .from('litters')
        .select('id, dam_id, breed_date, ultrasound_date, xray_date, due_date, whelp_date, go_home_date, status')
        .in('user_id', allUserIds);

    const dogById = {};
    (dogs || []).forEach(d => { dogById[d.id] = d; });

    const events = [];

    // Heat due (projected)
    (dogs || []).forEach(dog => {
        if (!dog.last_heat_date || !dog.avg_heat_cycle_days) return;
        const last = new Date(dog.last_heat_date).getTime();
        if (isNaN(last)) return;
        const cycleMs = dog.avg_heat_cycle_days * DAY_MS;
        let projected = last + cycleMs;
        let guard = 0;
        while (projected < windowStart && guard < 40) {
            projected += cycleMs;
            guard++;
        }
        while (projected <= windowEnd && guard < 80) {
            const iso = isoDate(new Date(projected));
            if (iso) {
                events.push({
                    uid: `heat-${dog.id}-${iso}@breediq.ai`,
                    type: 'heat_due',
                    date: iso,
                    summary: `Heat window — ${dog.name}`,
                    description: `Projected heat cycle for ${dog.name} based on a ${dog.avg_heat_cycle_days}-day average.`
                });
            }
            projected += cycleMs;
            guard++;
        }
    });

    // Vet visit overdue
    const oneYearAgo = now - 365 * DAY_MS;
    (dogs || []).forEach(dog => {
        if (!dog.vet_last_visit) return;
        const lastVisit = new Date(dog.vet_last_visit).getTime();
        if (isNaN(lastVisit) || lastVisit > oneYearAgo) return;
        const todayIso = isoDate(new Date(now));
        if (!todayIso) return;
        events.push({
            uid: `vet-${dog.id}@breediq.ai`,
            type: 'vet_due',
            date: todayIso,
            summary: `Vet visit overdue — ${dog.name}`,
            description: `${dog.name} has not had a recorded vet visit in over a year.`
        });
    });

    // Litter lifecycle events
    (litters || []).forEach(litter => {
        const dam = dogById[litter.dam_id];
        const damName = dam ? dam.name : 'Litter';

        const fields = [
            { key: 'breed_date',      type: 'breed' },
            { key: 'ultrasound_date', type: 'ultrasound' },
            { key: 'xray_date',       type: 'xray' },
            { key: 'due_date',        type: 'due' },
            { key: 'whelp_date',      type: 'whelp' },
            { key: 'go_home_date',    type: 'go_home' }
        ];

        fields.forEach(({ key, type }) => {
            const raw = litter[key];
            const iso = isoDate(raw);
            if (!withinWindow(iso, windowStart, windowEnd)) return;
            events.push({
                uid: `${type}-${litter.id}@breediq.ai`,
                type,
                date: iso,
                summary: `${damName} — ${EVENT_META[type].label}`,
                description: `Litter ${type.replace('_', ' ')} for ${damName}.`
            });
        });
    });

    return events;
}

// ─── ICS serialisation ───────────────────────────────────────

function renderIcs(events, { calendarName }) {
    const stamp = icsDateTimeUtc(new Date());
    const lines = [
        'BEGIN:VCALENDAR',
        'VERSION:2.0',
        'PRODID:-//BreedIQ//Calendar Feed//EN',
        'CALSCALE:GREGORIAN',
        'METHOD:PUBLISH',
        `X-WR-CALNAME:${escapeText(calendarName)}`,
        `X-WR-CALDESC:${escapeText('BreedIQ breeding events — heats, litters, whelp and go-home dates.')}`,
        'X-PUBLISHED-TTL:PT1H',
        'REFRESH-INTERVAL;VALUE=DURATION:PT1H'
    ];

    events.forEach(ev => {
        const dtstart = icsDate(ev.date);
        // All-day VEVENT: DTEND is the exclusive end (next day).
        const dtend = icsDate(addDays(ev.date, 1));
        lines.push('BEGIN:VEVENT');
        lines.push(`UID:${ev.uid}`);
        lines.push(`DTSTAMP:${stamp}`);
        lines.push(`DTSTART;VALUE=DATE:${dtstart}`);
        lines.push(`DTEND;VALUE=DATE:${dtend}`);
        lines.push(`SUMMARY:${escapeText(ev.summary)}`);
        if (ev.description) lines.push(`DESCRIPTION:${escapeText(ev.description)}`);
        lines.push('TRANSP:TRANSPARENT');
        lines.push('END:VEVENT');
    });

    lines.push('END:VCALENDAR');

    // Fold lines per RFC 5545 and join with CRLF.
    return lines.map(foldLine).join('\r\n') + '\r\n';
}

// ─── Handler ─────────────────────────────────────────────────

export default async function handler(req, res) {
    if (req.method !== 'GET' && req.method !== 'HEAD') {
        res.setHeader('Allow', 'GET, HEAD');
        return res.status(405).json({ error: 'Method not allowed' });
    }

    // Token comes from the dynamic segment. Vercel strips the .ics via the
    // rewrite in vercel.json, so req.query.token is the bare random string.
    let token = req.query && req.query.token;
    if (Array.isArray(token)) token = token[0];
    if (typeof token === 'string') {
        // Defensive: strip a trailing .ics if the rewrite ever mis-applies.
        token = token.replace(/\.ics$/i, '').trim();
    }

    if (!token || token.length < 16) {
        res.setHeader('Cache-Control', 'no-store');
        return res.status(404).send('Not found');
    }

    try {
        const supabase = getServiceClient();

        const { data: profile, error: profileErr } = await supabase
            .from('profiles')
            .select('id, full_name, kennel_name')
            .eq('calendar_feed_token', token)
            .maybeSingle();

        if (profileErr) {
            console.error('ICS feed profile lookup error:', profileErr);
            res.setHeader('Cache-Control', 'no-store');
            return res.status(500).send('Internal server error');
        }

        if (!profile) {
            res.setHeader('Cache-Control', 'no-store');
            return res.status(404).send('Not found');
        }

        const calendarName = profile.kennel_name
            ? `${profile.kennel_name} — BreedIQ`
            : (profile.full_name ? `${profile.full_name} — BreedIQ` : 'BreedIQ Calendar');

        const events = await buildEvents(supabase, profile.id);
        const body = renderIcs(events, { calendarName });

        res.setHeader('Content-Type', 'text/calendar; charset=utf-8');
        res.setHeader('Content-Disposition', 'inline; filename="breediq.ics"');
        // Calendar apps poll roughly hourly; match that and keep the response private.
        res.setHeader('Cache-Control', 'private, max-age=3600');

        if (req.method === 'HEAD') {
            return res.status(200).end();
        }
        return res.status(200).send(body);
    } catch (err) {
        console.error('ICS feed error:', err);
        res.setHeader('Cache-Control', 'no-store');
        return res.status(500).send('Internal server error');
    }
}
